apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: travel
  namespace: staging
spec:
  minReplicas: 2
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: travel
  targetCPUUtilizationPercentage: 75
