# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
defaults: &defaults
  docker:
    - image: circleci/node:carbon
  working_directory: ~/travella-deploy-scripts

attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/travella-deploy-scripts

persist_to_workspace: &persist_to_workspace
  persist_to_workspace:
    root: .
    paths: .

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - *persist_to_workspace

  build:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Build Configuration files
          command: |
            chmod +x bin/test
            bin/test build
      - *persist_to_workspace
  test:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Install K8s deploy scripts
          command: sudo npm install -g rok8s-scripts
      - run:
          name: Run deploy scripts test
          command: |
            chmod +x bin/test
            bin/test lint
workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - test:
          requires:
            - checkout
            - build
