variable "project" {}
variable "owner" {}
variable "maintainer" {}
variable "bucket" {}
variable "credentials" {}
variable "product" {}
variable "machine_type" {}
variable "db_instance_tier" {}
variable "db_backup_start_time" {}
variable "db_user" {}
variable "db_password" {}
